load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "backaar",
    calculators = ["//mediapipe/graphs/portrait_segmentation:portrait_segmentation_gpu_deps"],
)